### ISSUE TITLE
How can I create an Item from jython/lucid?

### ISSUE THREAD

**Issue by lukaszolek** [OH-Jython-Scripters/lucid#2]
I would like to create an item like this:
Switch Garage_Gate {binding="xxx", autoupdate="false"}

How do I define "binding" and "autoupdate" with Lucid?

**Comment by 5iver** [comment]
The OH forum is a better place for this, but check in the [items module](https://github.com/OH-Jython-Scripters/lucid/blob/master/automation/lib/python/lucid/items.py). There is a very small bit of documentation for it in the [readme](https://github.com/OH-Jython-Scripters/openhab2-jython#module-openhabitems).
