### ISSUE TITLE
Rework the branches

### ISSUE THREAD

**Issue by besynnerlig** [OH-Jython-Scripters/lucid#5]
Current master branch doesn't work for latest openHab. I believe the current master branch should be saved so that changes for openHab 2.4 can be incorporated. I'm not sure about how this is done in the best way, maybe someone else in the team is willing to suggest how this should be done?

**Comment by Rick-Jongbloed** [comment]
I'm currently migrating to the 2.4+ structure, i'll try to keep it on my radar.
After playing around with Lucid and migrating all my scripts to it, i did think Lucid should extend the openhab-jython installation as a framework and not replace it.

**Comment by besynnerlig** [comment]
Hi Rick.

Lucid is currently being incorporated into openhab2-jython. Please have a look [here](https://github.com/OH-Jython-Scripters/openhab2-jython/issues/51#issuecomment-486417957)
